# Generated by Django 5.2 on 2025-04-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='newest',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
