# Generated by Django 5.2 on 2025-04-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_newest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='newest',
            field=models.BooleanField(default=False),
        ),
    ]
